#!/bin/bash --login

# uncomment the following two lines if you need to debug this script
# set -v      # Print script lines as they are read.
# set -x      # Print commands and their arguments as they are executed.

# PBS job options (name, compute nodes, job time)
#PBS -N CFD2LCS
#PBS -l select=1
#PBS -l walltime=00:05:00

# Replace [budget code] below with your project code (e.g. t01)
#PBS -A ecse0414

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the directory that the job was submitted from
# (remember this should be on the /work filesystem)
cd $PBS_O_WORKDIR

# Set the number of threads to 1
#   This prevents any system libraries from automatically
#   using threading.
export OMP_NUM_THREADS=1

# Launch the parallel job
#   Using 8 MPI processes and 24 MPI processes per node
aprun -n 8 ./CFD2LCS_TEST 4 2 1 >& stdouterror
